# Generated by Django 3.0.6 on 2020-06-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200528_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rost',
            options={'ordering': ['-date_pub']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='rost',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='rost',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
