# Generated by Django 3.0.6 on 2020-06-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200602_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rost',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='blogengine/static/images/girls/', verbose_name='Your Photo'),
        ),
    ]
