# Generated by Django 3.0.6 on 2020-06-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200602_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rost',
            name='img',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Your Photo'),
        ),
    ]
